# Generated by Django 3.2 on 2021-04-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('discipline', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('name', 'discipline')},
            },
        ),
    ]
